kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: clusterip-gateway-test
nodes:
- role: control-plane
- role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
